#include "TIMER_DELAY.h"

// Pull in the TIM6 handle generated by CubeMX inside main.c
extern TIM_HandleTypeDef htim6;

// Flag to track the timer state.
// 1 = Finished/Idle, 0 = Currently counting
volatile uint8_t delay_finished_flag = 1;

/**
 * @brief Starts the hardware timer for a specific microsecond duration.
 * This function returns instantly, allowing the CPU to do other things.
 */
void Start_NonBlocking_Delay_us(uint16_t delay_us)
{
    // 1. Lock the flag so the main loop knows we are waiting
    delay_finished_flag = 0;

    // 2. Set the target microsecond delay into the timer's register
    __HAL_TIM_SET_AUTORELOAD(&htim6, delay_us);

    // 3. Reset the timer counter back to 0
    __HAL_TIM_SET_COUNTER(&htim6, 0);

    // 4. Start the timer with interrupts enabled
    HAL_TIM_Base_Start_IT(&htim6);
}

/**
 * @brief Checks if the hardware timer has finished its countdown.
 */
uint8_t Is_Delay_Finished(void)
{
    return delay_finished_flag;
}

/**
 * @brief The STM32 automatically jumps to this callback the exact
 * microsecond the TIM6 countdown finishes.
 */

